#!/bin/bash

time=$1
shift
oldoutput=""

while [ : ] ; do
    newoutput=$($@)
    echo "$newoutput" 
    if [ "$oldoutput" ] ; then
       diff -u <(echo "$oldoutput") <(echo "$newoutput") 
    fi
    oldoutput="$newoutput"
    sleep "$time"
done
